version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  version: 3.12
  install:
    - requirements: doc/requirements.txt

build:
  image: python:3.12
  commands:
    - pip install pdoc
    - pdoc --html -o doc sdrcap

