version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands: 
      - mkdir --parents _readthedocs/html/
      - cp --recursive doc/* _readthedocs/html/

python:
  install:
    - requirements: requirements.txt

